-- Executa no Supabase → SQL Editor (uma vez). Não dá erro se já estiver configurado.

do $rl$ begin alter publication supabase_realtime add table public.calendar_events; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.tasks; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.journal_spaces; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.journal_blocks; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.journal_note_layout; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.wishlist_groups; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.wishlist_items; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.finance_categories; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.expenses; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.income_categories; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.incomes; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.synapse_projects; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.project_stock; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.project_investments; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.project_notes; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.project_kpis; exception when others then null; end $rl$;
do $rl$ begin alter publication supabase_realtime add table public.project_inventory; exception when others then null; end $rl$;
